### ISSUE TITLE
Could not find a declaration file for module

### ISSUE THREAD

**Issue by beeme1mr** [splitio/split-openfeature-provider-js#1]
It looks like the typing information is missing or not exported properly from the package.

This is the error I'm seeing in VSCode

![image](https://user-images.githubusercontent.com/682996/192860035-6bbd4ee8-fa0b-4686-b012-aaeb00b8131a.png)

The npm package looks like this.

![image](https://user-images.githubusercontent.com/682996/192860458-ade5cc00-55ab-45ab-be7f-c56ae309224b.png)

**Comment by joshsirota** [comment]
Should be fixed now. Version is still 1.0.2.

**Comment by joshsirota** [comment]
Actually, updated to 1.0.3!
