### ISSUE TITLE
Is the targetingKey the MTK?  

### ISSUE THREAD

**Issue by ctaity** [splitio/split-openfeature-provider-js#4]
Is It the targetingKey the MTK?

**Comment by patricioe** [comment]
hey, sorry for the delay. Yes. That would be the same key you use for targeting that Split computes as MTK. 

Are you a current Split customer? Just curious.

**Comment by rgrassian-split** [comment]
We are closing this issue, please see answer above

**Comment by zzlatkov92** [comment]
@patricioe where can I get the `targetingKey/MTK `from ? I'm getting a **FLAG_NOT_FOUND** error and I'm not sure if it's because I pass a **wrong value** for `targetingKey`.

**Comment by zzlatkov92** [comment]
@rgrassian-split I have exactly that. I have created a feature flag, called `test1`, but I still get 404. 

```js
const context = {
    targetingKey: 'MY-TEST-ACCOUNT-KEY'
  };

useEffect(() => {
    const init = async () => {
      const flagValue = await client.getBooleanDetails('test1', false, context);

      console.log({ flagValue })
    }

    init()
  }, [])
```

**Comment by patricioe** [comment]
@zzlatkov92 hey, are you passing/using the correct API key during the initialization? Are you a current Split customer?

**Comment by patricioe** [comment]
So me a favor to validate a theory. Can you add some wait after you get that error for let's say, 5 seconds, and then call the flag again and report back?

**Comment by patricioe** [comment]
and also, do you see this log line at all?

``` 
console.log(`${this.metadata.name} provider initialized`);
```

**Comment by zzlatkov92** [comment]
> and also, do you see this log line at all?
> 
> ```
> console.log(`${this.metadata.name} provider initialized`);
> ```

Yes I do and after that I get the error. I will test your theory now and come back to you.

**Comment by patricioe** [comment]
Random. Are you using the API key from Split that belongs to the Stage environment?

Can you try to curl command using the same API key and the workspace Id and environment ID to match (staging) as per your screenshot?
https://docs.split.io/reference/list-feature-flags

**Comment by zzlatkov92** [comment]
> Random. Are you using the API key from Split that belongs to the Stage environment?
> 
> Can you try to curl command using the same API key and the workspace Id and environment ID to match (staging) as per your screenshot? https://docs.split.io/reference/list-feature-flags

I may be confused, but since I run my demo app on **localhost**, should I be checking [this](https://help.split.io/hc/en-us/articles/360020448791-JavaScript-SDK#localhost-mode) instead ?

**Comment by patricioe** [comment]
That is not needed unless you don't want to connect with the cloud and mock
the client.

Try the curl command when you have time

**Comment by zzlatkov92** [comment]
I tried the curl command also and I noticed the following things:

* for the **curl command**, it makes **requests** to this **REST** https://api.split.io. Here I need to pass `API key` for `Bearer token`. When I **authenticate** I can get the **feature flag by name**.
* in my case the app is calling a different **REST** from the one I mention above. It's calling https://sdk.split.io/api. For this one I need to use the `SDK key` to **authenticate** and here I **don't get my feature flag by name**.

This is where I am confused, why the difference in response ?!

**Comment by zzlatkov92** [comment]
yeah I will check with them, thank you
